### ISSUE TITLE
/boot/loader/ not being a link should not raise an error

### ISSUE THREAD

**Issue by BrunoVernay** [larsks/ostree#1]
OSTree raises an error if `/boot/loader/` is not a link: https://github.com/larsks/ostree/blob/master/src/libostree/ostree-sysroot.c#L519 
But Grub2 (and Fedora 29) creates a regular directory:  https://src.fedoraproject.org/rpms/grub2/blob/master/f/20-grub.install#_80 

In my case `/boot/loader` was empty. I had to manually create to please ostree. https://discussion.fedoraproject.org/t/not-a-symbolic-link-boot-loader/683 

(_I  also raised an issue in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1648672 , maybe they should create a link_)

**Comment by larsks** [comment]
Hi Bruno. I'm not sure how you found your way here, but this is simply an (very old) fork of https://github.com/ostreedev/ostree. The code here is several years out of date and was never for anything more than personal development work. If you're using ostree, you should file bugs against the actual upstream project and ensure you're using recent code.
